"""
Notion Integration for Firm & Fund Database Sync

Monitors a local folder for new firm/fund directories and syncs them
to Notion databases, uploading files and linking related pages.

Folder structure expected:
    {WATCH_FOLDER}/
    ├── {FIRM_NAME}/
    │   ├── file1.pdf                     (firm-level file)
    │   ├── {FUND_NAME} - {IDENTIFIER}/   (fund subfolder)
    │   │   ├── factsheet.pdf
    │   │   └── report.xlsx
    │   └── {FUND_NAME2} - {ID2}/
    │       └── ...

Usage:
    poetry run python -m fofproject.notion
    poetry run python -m fofproject.notion --folder "C:/path/to/watch"
"""

from dotenv import load_dotenv
from pathlib import Path
import json
import os
import re
import time
import mimetypes
import logging
import threading

import requests
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

# Load .env from the same directory as this script
env_path = Path(__file__).parent / ".env"
load_dotenv(dotenv_path=env_path)

# =========================
# CONFIGURATION
# =========================
NOTION_SECRET = os.getenv("NOTION_SECRET")
NOTION_VERSION = "2025-09-03"
BASE_URL = "https://api.notion.com/v1"

# Default watch folder — resolved relative to project root
_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_WATCH_FOLDER = _PROJECT_ROOT / "output" / "testing" / "notion" / "firm"

# Fund subfolder pattern: "{FUND_NAME} - {IDENTIFIER}"
FUND_FOLDER_PATTERN = re.compile(r"^(.+?)\s*-\s*(\d+)$")

# Prefix used by performance.py to flag identifier conflicts
CONFLICT_IDENTIFIER_PREFIX = "404 multiple identifier"

# File size limit for single-part upload (20 MB)
MAX_SINGLE_UPLOAD_BYTES = 20 * 1024 * 1024

# Fund page Data Packs section names (H2 headings in the template)
SECTION_PRESENTATION = "Presentation"
SECTION_MONTHLY_LETTERS = "Monthly Letters"
SECTION_OTHERS = "Others"

# Keywords used to classify files into sections (case-insensitive)
PRESENTATION_KEYWORDS = [
    "deck", "presentation", "overview", "pitch", "ppt",
]
MONTHLY_LETTERS_KEYWORDS = [
    "factsheet", "tearsheet", "tear sheet", "fact sheet",
    "investor letter", "monthly letter", "newsletter",
    "monthly report", "monthly update",
]

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)

# Thread-safe guard to prevent re-uploading files that the poller just downloaded.
# Uses a time-based TTL: guarded paths expire after GUARD_TTL_SECONDS so the
# watchdog skips all events (created, modified, etc.) that fire during/after download.
GUARD_TTL_SECONDS = 30
_download_guard: dict[str, float] = {}   # norm_path -> timestamp
_download_guard_lock = threading.Lock()


def _guard_path(file_path: Path):
    """Add a file path to the download guard (call before writing to disk)."""
    norm = str(file_path.resolve()).replace("\\", "/").lower()
    with _download_guard_lock:
        _download_guard[norm] = time.time()


def _check_guard(file_path: Path) -> bool:
    """Check if a file was recently downloaded by the poller.

    Returns True if the file should be skipped (was downloaded within the TTL window).
    Expired entries are cleaned up lazily.
    """
    norm = str(file_path.resolve()).replace("\\", "/").lower()
    now = time.time()
    with _download_guard_lock:
        ts = _download_guard.get(norm)
        if ts is not None:
            if now - ts < GUARD_TTL_SECONDS:
                return True  # still within TTL — skip this file
            # Expired — clean up
            del _download_guard[norm]
    return False


# =========================
# PROXY MANIFEST
# =========================
# Tracks files generated by the poller (meeting note PDFs, nested page PDFs).
# These are "proxy" files that mirror Notion content and must NOT be re-uploaded.
# Stored as .notion_proxies.json in each fund folder.

PROXY_MANIFEST_NAME = ".notion_proxies.json"


def _load_proxy_manifest(folder: Path) -> dict[str, dict]:
    """Load the proxy manifest for a fund folder.

    Returns: {normalized_filename: {"page_id": str, "title": str, "filename": str}}
    """
    manifest_path = folder / PROXY_MANIFEST_NAME
    if not manifest_path.exists():
        return {}
    try:
        return json.loads(manifest_path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _save_proxy_manifest(folder: Path, manifest: dict[str, dict]):
    """Save the proxy manifest for a fund folder."""
    manifest_path = folder / PROXY_MANIFEST_NAME
    manifest_path.write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


def _is_proxy_file(file_path: Path) -> bool:
    """Check if a file is a poller-generated proxy (should not be uploaded)."""
    folder = file_path.parent
    manifest = _load_proxy_manifest(folder)
    norm = _normalize_filename(file_path.name)
    return norm in manifest


# =========================
# LOW-LEVEL API HELPERS
# =========================

def _headers(content_type: str = "application/json") -> dict:
    """Return standard Notion API headers."""
    if not NOTION_SECRET:
        raise ValueError(
            "NOTION_SECRET not found in environment variables. "
            "Add it to src/fofproject/.env"
        )
    h = {
        "Authorization": f"Bearer {NOTION_SECRET}",
        "Notion-Version": NOTION_VERSION,
    }
    if content_type:
        h["Content-Type"] = content_type
    return h


def _notion_request(method: str, endpoint: str, **kwargs) -> dict:
    """Make a Notion API request with retry logic for rate limits and gateway timeouts."""
    url = f"{BASE_URL}{endpoint}" if endpoint.startswith("/") else endpoint
    kwargs.setdefault("headers", _headers())
    kwargs.setdefault("timeout", 30)

    retryable_statuses = {429, 502, 503, 504}
    max_retries = 5

    for attempt in range(max_retries):
        try:
            resp = getattr(requests, method)(url, **kwargs)
        except requests.exceptions.Timeout:
            if attempt < max_retries - 1:
                wait = 2 ** attempt
                log.warning("Request timed out, retrying in %ds... (attempt %d/%d)",
                            wait, attempt + 1, max_retries)
                time.sleep(wait)
                continue
            raise

        if resp.status_code in retryable_statuses:
            if resp.status_code == 429:
                wait = int(resp.headers.get("Retry-After", 2))
            else:
                wait = 2 ** attempt  # exponential backoff: 1, 2, 4, 8, 16s
            log.warning(
                "Notion API %d on %s %s, retrying in %ds... (attempt %d/%d)",
                resp.status_code, method.upper(), endpoint,
                wait, attempt + 1, max_retries,
            )
            time.sleep(wait)
            continue

        if resp.status_code >= 400:
            log.error(
                "Notion API error %d: %s", resp.status_code, resp.text
            )
            resp.raise_for_status()
        return resp.json()

    resp.raise_for_status()
    return {}


def _search_databases() -> list[dict]:
    """Search for all databases the integration can access."""
    results = []
    start_cursor = None

    while True:
        body: dict = {
            "filter": {"property": "object", "value": "data_source"},
        }
        if start_cursor:
            body["start_cursor"] = start_cursor

        data = _notion_request("post", "/search", json=body)
        for item in data.get("results", []):
            title_parts = item.get("title", [])
            title = "".join(t.get("plain_text", "") for t in title_parts)
            results.append({"id": item["id"], "title": title})

        if not data.get("has_more"):
            break
        start_cursor = data.get("next_cursor")

    return results


def discover_databases() -> tuple[str, str]:
    """
    Auto-discover the Firm and Fund database IDs.

    Returns:
        (firm_db_id, fund_db_id)
    """
    databases = _search_databases()
    log.info("Found %d databases: %s", len(databases),
             [d["title"] for d in databases])

    firm_db_id = None
    fund_db_id = None

    for db in databases:
        title_lower = db["title"].lower()
        if "firm" in title_lower and firm_db_id is None:
            firm_db_id = db["id"]
            log.info("Firm database: %s (%s)", db["title"], db["id"])
        if "fund" in title_lower and fund_db_id is None:
            fund_db_id = db["id"]
            log.info("Fund database: %s (%s)", db["title"], db["id"])

    if not firm_db_id:
        raise RuntimeError(
            f"Could not find a database with 'Firm' in its title. "
            f"Available databases: {[d['title'] for d in databases]}"
        )
    if not fund_db_id:
        raise RuntimeError(
            f"Could not find a database with 'Fund' in its title. "
            f"Available databases: {[d['title'] for d in databases]}"
        )

    return firm_db_id, fund_db_id


def _query_database_by_title(
    db_id: str, title: str, title_property: str = "Name",
) -> dict | None:
    """Query a database for a page with the given title. Returns page or None."""
    body = {
        "filter": {
            "property": title_property,
            "title": {"equals": title},
        },
        "page_size": 1,
    }
    data = _notion_request("post", f"/data_sources/{db_id}/query", json=body)
    results = data.get("results", [])
    return results[0] if results else None


# Title property names per database (discovered from schema)
FIRM_TITLE_PROP = "Doc name"
FUND_TITLE_PROP = "Fund Name"


def _create_page(
    db_id: str,
    title: str,
    title_property: str = "Name",
    extra_properties: dict | None = None,
    use_template: bool = True,
) -> str:
    """
    Create a new page in a Notion database.

    Args:
        db_id: Database ID
        title: Page title
        title_property: Name of the title property in the database schema
        extra_properties: Additional properties to set (e.g. Identifier, relations)
        use_template: Whether to apply the database's default template

    Returns:
        The created page ID
    """
    properties = {
        title_property: {
            "title": [{"type": "text", "text": {"content": title}}]
        }
    }
    if extra_properties:
        properties.update(extra_properties)

    body: dict = {
        "parent": {"data_source_id": db_id},
        "properties": properties,
    }
    if use_template:
        body["template"] = {"type": "default"}

    data = _notion_request("post", "/pages", json=body)
    page_id = data["id"]
    log.info("Created page '%s' -> %s", title, page_id)
    return page_id


def _update_page_properties(page_id: str, properties: dict) -> dict:
    """Update properties on an existing page."""
    body = {"properties": properties}
    return _notion_request("patch", f"/pages/{page_id}", json=body)


# =========================
# FILE UPLOAD
# =========================

def _get_block_type(file_path: Path) -> str:
    """Determine the Notion block type for a file.

    Always returns 'file' so documents appear as clickable attachments
    rather than inline embeds (e.g. PDFs won't auto-expand on the page).
    """
    return "file"


def _get_mime_type(file_path: Path) -> str:
    """Get MIME type for a file."""
    mime, _ = mimetypes.guess_type(str(file_path))
    return mime or "application/octet-stream"


def _upload_file(file_path: Path) -> str | None:
    """
    Upload a file to Notion and return the file_upload_id.

    Returns None if the file is too large or upload fails.
    """
    file_size = file_path.stat().st_size
    if file_size > MAX_SINGLE_UPLOAD_BYTES:
        log.warning(
            "Skipping '%s' — file is %.1f MB (max %d MB for single upload)",
            file_path.name,
            file_size / (1024 * 1024),
            MAX_SINGLE_UPLOAD_BYTES // (1024 * 1024),
        )
        return None

    try:
        # Step 1: Create file upload object
        create_body = {
            "filename": file_path.name,
            "content_type": _get_mime_type(file_path),
        }
        create_resp = _notion_request(
            "post", "/file_uploads", json=create_body
        )
        upload_id = create_resp["id"]
    except requests.HTTPError as e:
        log.warning(
            "Skipping '%s' — unsupported by Notion File Upload API: %s",
            file_path.name, e,
        )
        return None

    # Step 2: Send file content (with retry for gateway timeouts)
    send_url = f"{BASE_URL}/file_uploads/{upload_id}/send"
    send_headers = {
        "Authorization": f"Bearer {NOTION_SECRET}",
        "Notion-Version": NOTION_VERSION,
    }
    retryable = {429, 502, 503, 504}
    send_resp = None

    for attempt in range(5):
        with open(file_path, "rb") as f:
            try:
                send_resp = requests.post(
                    send_url,
                    headers=send_headers,
                    files={"file": (file_path.name, f, _get_mime_type(file_path))},
                    timeout=120,
                )
            except requests.exceptions.Timeout:
                if attempt < 4:
                    wait = 2 ** attempt
                    log.warning("File send timed out for '%s', retrying in %ds...",
                                file_path.name, wait)
                    time.sleep(wait)
                    continue
                log.error("File send timed out for '%s' after retries", file_path.name)
                return None

        if send_resp.status_code in retryable:
            wait = int(send_resp.headers.get("Retry-After", 2 ** attempt))
            log.warning("File send got %d for '%s', retrying in %ds...",
                        send_resp.status_code, file_path.name, wait)
            time.sleep(wait)
            continue
        break

    if send_resp is None or send_resp.status_code >= 400:
        log.error(
            "Failed to send file '%s': %d %s",
            file_path.name,
            send_resp.status_code if send_resp else 0,
            send_resp.text if send_resp else "no response",
        )
        return None

    log.info("Uploaded file '%s' -> %s", file_path.name, upload_id)
    return upload_id


def _extract_filename_from_url(url: str) -> str | None:
    """Extract the filename from a Notion S3 URL (keeps underscores as-is)."""
    from urllib.parse import urlparse, unquote
    try:
        path = urlparse(url).path
        encoded_name = path.rsplit("/", 1)[-1]
        return unquote(encoded_name)
    except Exception:
        return None


def _normalize_filename(name: str) -> str:
    """Normalize a filename for comparison (spaces <-> underscores)."""
    return name.replace(" ", "_").lower()


def _delete_block(block_id: str):
    """Delete a Notion block by ID."""
    _notion_request("delete", f"/blocks/{block_id}")
    log.info("Deleted block %s", block_id)


def _find_file_block_ids_in_children(
    parent_id: str, normalized_name: str,
) -> list[str]:
    """Find all file block IDs under a parent that match the given normalized filename."""
    matching = []
    file_block_types = {"file", "pdf", "image", "audio", "video"}
    start_cursor = None

    while True:
        params = {"page_size": 100}
        if start_cursor:
            params["start_cursor"] = start_cursor
        data = _notion_request(
            "get", f"/blocks/{parent_id}/children", params=params
        )
        for block in data.get("results", []):
            btype = block.get("type", "")
            if btype in file_block_types:
                block_data = block.get(btype, {})
                name = block_data.get("name")
                if not name:
                    file_info = block_data.get("file", {})
                    url = file_info.get("url", "")
                    if url:
                        name = _extract_filename_from_url(url)
                if name and _normalize_filename(name) == normalized_name:
                    matching.append(block["id"])
        if not data.get("has_more"):
            break
        start_cursor = data.get("next_cursor")

    return matching


def _remove_file_from_page(page_id: str, filename: str):
    """Remove all file blocks matching filename from a page and its section callouts."""
    norm = _normalize_filename(filename)

    # Check page-level children
    block_ids = _find_file_block_ids_in_children(page_id, norm)

    # Also check inside section callout blocks (fund pages)
    section_callouts = _find_section_callout_ids(page_id)
    for callout_id in section_callouts.values():
        block_ids.extend(_find_file_block_ids_in_children(callout_id, norm))

    if block_ids:
        for bid in block_ids:
            _delete_block(bid)
        log.info("Removed %d block(s) for file '%s' from page %s",
                 len(block_ids), filename, page_id)
    else:
        log.warning("File '%s' not found on page %s", filename, page_id)


def _rename_page_title(page_id: str, new_title: str, title_property: str):
    """Rename a page by updating its title property."""
    _update_page_properties(page_id, {
        title_property: {
            "title": [{"type": "text", "text": {"content": new_title}}]
        }
    })
    log.info("Renamed page %s to '%s'", page_id, new_title)


def _remove_file_from_firm_property(page_id: str, filename: str):
    """Remove a file from the 'Firm Documents' files property."""
    norm = _normalize_filename(filename)
    page_data = _notion_request("get", f"/pages/{page_id}")
    existing_files = page_data.get("properties", {}).get("Firm Documents", {}).get("files", [])

    updated = [
        f for f in existing_files
        if _normalize_filename(f.get("name", "")) != norm
    ]

    if len(updated) == len(existing_files):
        log.warning("File '%s' not found in Firm Documents property", filename)
        return

    _update_page_properties(page_id, {
        "Firm Documents": {"files": updated}
    })
    log.info("Removed '%s' from Firm Documents property on page %s",
             filename, page_id)


def _get_existing_filenames_normalized(page_id: str) -> set[str]:
    """Get normalized filenames of files already attached to a page."""
    filenames = set()
    start_cursor = None
    file_block_types = {"file", "pdf", "image", "audio", "video"}

    while True:
        params = {"page_size": 100}
        if start_cursor:
            params["start_cursor"] = start_cursor
        data = _notion_request(
            "get", f"/blocks/{page_id}/children", params=params
        )
        for block in data.get("results", []):
            btype = block.get("type", "")
            if btype in file_block_types:
                block_data = block.get(btype, {})
                name = block_data.get("name")
                if not name:
                    file_info = block_data.get("file", {})
                    url = file_info.get("url", "")
                    if url:
                        name = _extract_filename_from_url(url)
                if name:
                    filenames.add(_normalize_filename(name))
        if not data.get("has_more"):
            break
        start_cursor = data.get("next_cursor")

    return filenames


def _attach_files_to_page(page_id: str, file_infos: list[tuple[Path, str]]):
    """
    Attach uploaded files to a page as child blocks.

    Args:
        page_id: The Notion page to attach files to
        file_infos: List of (file_path, file_upload_id) tuples
    """
    if not file_infos:
        return

    children = []
    for file_path, upload_id in file_infos:
        block_type = _get_block_type(file_path)
        children.append({
            "type": block_type,
            block_type: {
                "type": "file_upload",
                "file_upload": {"id": upload_id},
            },
        })

    # Notion allows max 100 blocks per request
    for i in range(0, len(children), 100):
        batch = children[i:i + 100]
        _notion_request(
            "patch",
            f"/blocks/{page_id}/children",
            json={"children": batch},
        )
        log.info(
            "Attached %d file(s) to page %s", len(batch), page_id
        )


# =========================
# FUND PAGE SECTION HANDLING
# =========================

def _classify_file(file_path: Path) -> str:
    """
    Classify a file into a Data Packs section based on its filename.

    Returns one of: SECTION_PRESENTATION, SECTION_MONTHLY_LETTERS, SECTION_OTHERS
    """
    name_lower = file_path.name.lower()
    for kw in PRESENTATION_KEYWORDS:
        if kw in name_lower:
            return SECTION_PRESENTATION
    for kw in MONTHLY_LETTERS_KEYWORDS:
        if kw in name_lower:
            return SECTION_MONTHLY_LETTERS
    return SECTION_OTHERS


def _find_section_callout_ids(page_id: str) -> dict[str, str]:
    """
    Find the callout block IDs for each Data Packs section on a fund page.

    The template structure is:
        H1: Data Packs
          H2: Presentation
          callout (children go here)
          H2: Monthly Letters
          callout (children go here)
          H2: Others
          callout (children go here)

    Returns: {"Presentation": callout_id, "Monthly Letters": callout_id, "Others": callout_id}
    """
    start_cursor = None
    all_blocks = []
    while True:
        params = {"page_size": 100}
        if start_cursor:
            params["start_cursor"] = start_cursor
        data = _notion_request(
            "get", f"/blocks/{page_id}/children", params=params
        )
        all_blocks.extend(data.get("results", []))
        if not data.get("has_more"):
            break
        start_cursor = data.get("next_cursor")

    section_callouts = {}
    current_h2 = None
    in_data_packs = False

    for block in all_blocks:
        btype = block.get("type", "")

        if btype == "heading_1":
            text_parts = block.get(btype, {}).get("rich_text", [])
            text = "".join(t.get("plain_text", "") for t in text_parts)
            in_data_packs = "data packs" in text.lower()
            current_h2 = None

        elif btype == "heading_2" and in_data_packs:
            text_parts = block.get(btype, {}).get("rich_text", [])
            current_h2 = "".join(t.get("plain_text", "") for t in text_parts).strip()

        elif btype == "callout" and in_data_packs and current_h2:
            section_callouts[current_h2] = block["id"]
            current_h2 = None  # Only take the first callout after each H2

    return section_callouts


def _get_existing_filenames_in_block(block_id: str) -> set[str]:
    """Get normalized filenames of files that are children of a specific block."""
    filenames = set()
    file_block_types = {"file", "pdf", "image", "audio", "video"}
    start_cursor = None

    while True:
        params = {"page_size": 100}
        if start_cursor:
            params["start_cursor"] = start_cursor
        data = _notion_request(
            "get", f"/blocks/{block_id}/children", params=params
        )
        for child in data.get("results", []):
            btype = child.get("type", "")
            if btype in file_block_types:
                block_data = child.get(btype, {})
                name = block_data.get("name")
                if not name:
                    file_info = block_data.get("file", {})
                    url = file_info.get("url", "")
                    if url:
                        name = _extract_filename_from_url(url)
                if name:
                    filenames.add(_normalize_filename(name))
        if not data.get("has_more"):
            break
        start_cursor = data.get("next_cursor")

    return filenames


def _upload_files_to_sections(
    page_id: str,
    files: list[Path],
    section_callouts: dict[str, str],
):
    """
    Upload files into the correct Data Packs section callout on a fund page.

    Files are classified by name and uploaded as children of the matching
    callout block (Presentation, Monthly Letters, or Others).
    """
    # Group files by section
    by_section: dict[str, list[Path]] = {
        SECTION_PRESENTATION: [],
        SECTION_MONTHLY_LETTERS: [],
        SECTION_OTHERS: [],
    }
    for f in files:
        section = _classify_file(f)
        by_section[section].append(f)

    for section_name, section_files in by_section.items():
        if not section_files:
            continue

        callout_id = section_callouts.get(section_name)
        if not callout_id:
            log.warning(
                "Section '%s' callout not found on page, "
                "falling back to page-level attachment",
                section_name,
            )
            # Fallback: attach directly to page
            file_infos = []
            for f in section_files:
                uid = _upload_file(f)
                if uid:
                    file_infos.append((f, uid))
            _attach_files_to_page(page_id, file_infos)
            continue

        # Check existing files in this callout to skip duplicates
        existing = _get_existing_filenames_in_block(callout_id)
        new_files = [
            f for f in section_files
            if _normalize_filename(f.name) not in existing
        ]
        if len(new_files) < len(section_files):
            log.info(
                "Section '%s': skipping %d already-uploaded file(s)",
                section_name, len(section_files) - len(new_files),
            )
        if not new_files:
            continue

        # Upload and attach to the callout block
        file_infos = []
        for f in new_files:
            uid = _upload_file(f)
            if uid:
                file_infos.append((f, uid))

        if file_infos:
            children = []
            for file_path, upload_id in file_infos:
                block_type = _get_block_type(file_path)
                children.append({
                    "type": block_type,
                    block_type: {
                        "type": "file_upload",
                        "file_upload": {"id": upload_id},
                    },
                })

            for i in range(0, len(children), 100):
                batch = children[i:i + 100]
                _notion_request(
                    "patch",
                    f"/blocks/{callout_id}/children",
                    json={"children": batch},
                )
            log.info(
                "Attached %d file(s) to '%s' section",
                len(file_infos), section_name,
            )


def _wait_for_template(page_id: str, max_wait: int = 30) -> bool:
    """
    Wait for the async template to populate on a newly created page.

    Returns True if template blocks appeared, False if timed out.
    """
    for attempt in range(max_wait // 2):
        data = _notion_request(
            "get", f"/blocks/{page_id}/children", params={"page_size": 5}
        )
        if data.get("results"):
            return True
        log.info("Waiting for template to apply... (%ds)", (attempt + 1) * 2)
        time.sleep(2)
    log.warning("Template did not populate within %ds", max_wait)
    return False


def _upload_firm_files_to_property(page_id: str, files: list[Path]):
    """
    Upload firm-level files and set them on the 'Firm Documents' files property.

    Notion's files property requires file_upload references.
    """
    if not files:
        return

    # Get existing files in the property to avoid duplicates
    page_data = _notion_request("get", f"/pages/{page_id}")
    existing_files = page_data.get("properties", {}).get("Firm Documents", {}).get("files", [])
    existing_names = {
        _normalize_filename(f.get("name", "")) for f in existing_files
    }

    new_files = [
        f for f in files
        if _normalize_filename(f.name) not in existing_names
    ]
    if len(new_files) < len(files):
        log.info(
            "Skipping %d already-uploaded firm file(s)",
            len(files) - len(new_files),
        )
    if not new_files:
        return

    # Upload each file
    upload_entries = []
    # Keep existing file references
    for ef in existing_files:
        if ef.get("type") == "file":
            upload_entries.append(ef)
        elif ef.get("type") == "file_upload":
            upload_entries.append(ef)

    for f in new_files:
        uid = _upload_file(f)
        if uid:
            upload_entries.append({
                "type": "file_upload",
                "file_upload": {"id": uid},
                "name": f.name,
            })

    # Update the property
    _update_page_properties(page_id, {
        "Firm Documents": {
            "files": upload_entries,
        }
    })
    log.info("Updated Firm Documents with %d file(s)", len(upload_entries))


# =========================
# FOLDER PARSING
# =========================

def parse_fund_folder_name(folder_name: str) -> tuple[str, str] | None:
    """
    Parse a fund folder name into (fund_name, identifier).

    Expected format: "{FUND_NAME} - {NUMERIC_ID}"
    Returns None if the folder name doesn't match the pattern.
    """
    match = FUND_FOLDER_PATTERN.match(folder_name)
    if not match:
        return None
    return match.group(1).strip(), match.group(2).strip()


def _resolve_fund_name(folder_name: str) -> str:
    """
    Extract the fund name from a folder name.

    If the folder matches the pattern "{NAME} - {ID}", returns NAME.
    Otherwise returns the full folder name (for folders renamed without an identifier).
    """
    parsed = parse_fund_folder_name(folder_name)
    return parsed[0] if parsed else folder_name


def get_firm_contents(firm_path: Path) -> tuple[list[Path], list[Path]]:
    """
    Analyze a firm folder and separate firm-level files from fund subfolders.

    Returns:
        (firm_files, fund_folders)
    """
    firm_files = []
    fund_folders = []

    for item in firm_path.iterdir():
        if item.is_dir():
            if item.name.startswith(CONFLICT_IDENTIFIER_PREFIX):
                log.warning(
                    "Skipping fund folder '%s' — flagged as identifier conflict",
                    item.name,
                )
            elif parse_fund_folder_name(item.name):
                fund_folders.append(item)
            else:
                log.warning(
                    "Skipping subdirectory '%s' — doesn't match fund pattern "
                    "'{FUND_NAME} - {ID}'",
                    item.name,
                )
        elif item.is_file():
            firm_files.append(item)

    return firm_files, fund_folders


# =========================
# SYNC LOGIC
# =========================

def _upload_and_attach_files(page_id: str, files: list[Path]):
    """Upload a list of files and attach them to a Notion page, skipping duplicates."""
    existing = _get_existing_filenames_normalized(page_id)
    new_files = [f for f in files if _normalize_filename(f.name) not in existing]
    if len(new_files) < len(files):
        log.info(
            "Skipping %d already-uploaded file(s)", len(files) - len(new_files)
        )
    file_infos = []
    for f in new_files:
        upload_id = _upload_file(f)
        if upload_id:
            file_infos.append((f, upload_id))
    _attach_files_to_page(page_id, file_infos)


def sync_fund(
    fund_path: Path,
    fund_db_id: str,
    firm_page_id: str,
) -> str | None:
    """
    Sync a single fund folder to the Notion Fund database.

    Args:
        fund_path: Path to the fund folder
        fund_db_id: Notion Fund database ID
        firm_page_id: Notion page ID of the parent firm

    Returns:
        The fund page ID, or None if skipped
    """
    parsed = parse_fund_folder_name(fund_path.name)
    if not parsed:
        log.warning("Cannot parse fund folder name: '%s'", fund_path.name)
        return None

    fund_name, identifier = parsed
    log.info("Syncing fund: %s (identifier: %s)", fund_name, identifier)

    # Check if fund already exists
    existing = _query_database_by_title(fund_db_id, fund_name, FUND_TITLE_PROP)
    if existing:
        fund_page_id = existing["id"]
        log.info("Fund '%s' already exists -> %s", fund_name, fund_page_id)
    else:
        # Create fund page with Identifier and AM Firm relation
        extra_properties = {
            "Identifier": {
                "rich_text": [
                    {"type": "text", "text": {"content": identifier}}
                ]
            },
            "AM Firm": {
                "relation": [{"id": firm_page_id}]
            },
        }
        fund_page_id = _create_page(
            fund_db_id, fund_name,
            title_property=FUND_TITLE_PROP,
            extra_properties=extra_properties,
            use_template=True,
        )

    # Wait for template if we just created the page
    if not existing:
        _wait_for_template(fund_page_id)

    # Find section callout blocks from the template
    section_callouts = _find_section_callout_ids(fund_page_id)

    # Upload fund files into the correct sections (exclude manifest and proxies)
    proxy_manifest = _load_proxy_manifest(fund_path)
    fund_files = [
        f for f in fund_path.iterdir()
        if f.is_file()
        and f.name != PROXY_MANIFEST_NAME
        and _normalize_filename(f.name) not in proxy_manifest
    ]
    if fund_files:
        log.info("Uploading %d file(s) for fund '%s'", len(fund_files), fund_name)
        if section_callouts:
            _upload_files_to_sections(fund_page_id, fund_files, section_callouts)
        else:
            log.warning(
                "No Data Packs sections found on page, "
                "falling back to page-level upload"
            )
            _upload_and_attach_files(fund_page_id, fund_files)

    return fund_page_id


def sync_firm(firm_path: Path, firm_db_id: str, fund_db_id: str):
    """
    Sync a firm folder (and its fund subfolders) to Notion.

    Args:
        firm_path: Path to the firm folder
        firm_db_id: Notion Firm database ID
        fund_db_id: Notion Fund database ID
    """
    firm_name = firm_path.name
    log.info("=== Syncing firm: %s ===", firm_name)

    # Check if firm already exists
    existing = _query_database_by_title(firm_db_id, firm_name, FIRM_TITLE_PROP)
    if existing:
        firm_page_id = existing["id"]
        log.info("Firm '%s' already exists -> %s", firm_name, firm_page_id)
    else:
        firm_page_id = _create_page(
            firm_db_id, firm_name,
            title_property=FIRM_TITLE_PROP,
            use_template=True,
        )

    # Parse folder contents
    firm_files, fund_folders = get_firm_contents(firm_path)

    # Upload firm-level files to "Firm Documents" property
    if firm_files:
        log.info("Uploading %d firm-level file(s)", len(firm_files))
        _upload_firm_files_to_property(firm_page_id, firm_files)

    # Sync each fund subfolder
    fund_page_ids = []
    for fund_folder in fund_folders:
        fund_page_id = sync_fund(fund_folder, fund_db_id, firm_page_id)
        if fund_page_id:
            fund_page_ids.append(fund_page_id)

    # Update firm's "Managing Funds" relation to include all fund pages
    if fund_page_ids:
        _update_page_properties(firm_page_id, {
            "Managing Funds": {
                "relation": [{"id": pid} for pid in fund_page_ids]
            }
        })
        log.info(
            "Linked firm '%s' to %d fund(s)", firm_name, len(fund_page_ids)
        )

    log.info("=== Done syncing firm: %s ===", firm_name)


# =========================
# WATCHDOG HANDLER
# =========================

class NotionFolderHandler(FileSystemEventHandler):
    """Watches for new firm/fund folders and files, syncs to Notion."""

    def __init__(self, watch_folder: Path, firm_db_id: str, fund_db_id: str):
        super().__init__()
        self.watch_folder = watch_folder
        self.firm_db_id = firm_db_id
        self.fund_db_id = fund_db_id

    def on_created(self, event):
        if not event.is_directory:
            # A new file was added — figure out where it belongs
            self._handle_new_file(Path(event.src_path))
            return

        new_path = Path(event.src_path)
        parent = new_path.parent

        if parent == self.watch_folder:
            # New firm folder created
            log.info("New firm folder detected: %s", new_path.name)
            threading.Thread(
                target=sync_firm,
                args=(new_path, self.firm_db_id, self.fund_db_id),
                daemon=True,
            ).start()
        elif parent.parent == self.watch_folder:
            # New fund folder inside an existing firm
            if new_path.name.startswith(CONFLICT_IDENTIFIER_PREFIX):
                log.warning(
                    "Skipping new fund folder '%s' — identifier conflict",
                    new_path.name,
                )
                return
            parsed = parse_fund_folder_name(new_path.name)
            if parsed:
                log.info("New fund folder detected: %s", new_path.name)
                firm_name = parent.name
                existing_firm = _query_database_by_title(
                    self.firm_db_id, firm_name, FIRM_TITLE_PROP
                )
                if existing_firm:
                    threading.Thread(
                        target=sync_fund,
                        args=(
                            new_path,
                            self.fund_db_id,
                            existing_firm["id"],
                        ),
                        daemon=True,
                    ).start()
                else:
                    log.warning(
                        "Fund folder '%s' appeared but firm '%s' not found "
                        "in Notion. Syncing entire firm.",
                        new_path.name, firm_name,
                    )
                    threading.Thread(
                        target=sync_firm,
                        args=(parent, self.firm_db_id, self.fund_db_id),
                        daemon=True,
                    ).start()

    def _handle_new_file(self, file_path: Path):
        """Handle a new file added to an existing firm or fund folder."""
        # Skip the proxy manifest file itself
        if file_path.name == PROXY_MANIFEST_NAME:
            return

        # Skip files that were just downloaded by the poller (TTL guard)
        if _check_guard(file_path):
            log.debug("Skipping re-upload of downloaded file: %s", file_path.name)
            return

        # Skip proxy files (meeting note / nested page PDFs managed by poller)
        if _is_proxy_file(file_path):
            log.debug("Skipping proxy file (managed by Notion): %s", file_path.name)
            return

        parent = file_path.parent
        grandparent = parent.parent

        # File in a fund folder
        if grandparent.parent == self.watch_folder:
            fund_name = _resolve_fund_name(parent.name)
            existing_fund = _query_database_by_title(
                self.fund_db_id, fund_name, FUND_TITLE_PROP
            )
            if existing_fund:
                log.info(
                    "New file in fund '%s': %s",
                    fund_name, file_path.name,
                )
                threading.Thread(
                    target=self._upload_fund_file_to_section,
                    args=(existing_fund["id"], file_path),
                    daemon=True,
                ).start()
                return

        # File in a firm folder (direct child)
        if parent.parent == self.watch_folder:
            firm_name = parent.name
            existing_firm = _query_database_by_title(
                self.firm_db_id, firm_name, FIRM_TITLE_PROP
            )
            if existing_firm:
                log.info(
                    "New file in firm '%s': %s",
                    firm_name, file_path.name,
                )
                threading.Thread(
                    target=_upload_firm_files_to_property,
                    args=(existing_firm["id"], [file_path]),
                    daemon=True,
                ).start()

    def _upload_fund_file_to_section(self, fund_page_id: str, file_path: Path):
        """Upload a single fund file into the correct Data Packs section."""
        section_callouts = _find_section_callout_ids(fund_page_id)
        if section_callouts:
            _upload_files_to_sections(fund_page_id, [file_path], section_callouts)
        else:
            log.warning(
                "No Data Packs sections found on page %s, "
                "falling back to page-level upload",
                fund_page_id,
            )
            _upload_and_attach_files(fund_page_id, [file_path])

    def on_deleted(self, event):
        """Handle file or folder deletion — remove corresponding content from Notion."""
        if event.is_directory:
            return

        deleted_path = Path(event.src_path)
        parent = deleted_path.parent
        filename = deleted_path.name

        # Skip the proxy manifest file
        if filename == PROXY_MANIFEST_NAME:
            return

        # Skip files deleted by the poller (TTL guard from stale proxy cleanup)
        if _check_guard(deleted_path):
            log.debug("Skipping Notion deletion for poller-managed file: %s", filename)
            return

        # Skip proxy files — these are managed by the poller and mirror Notion state.
        # When the poller deletes a stale proxy, we must NOT propagate that to Notion.
        # Note: the file is already gone, so we check the manifest directly.
        manifest = _load_proxy_manifest(parent)
        if _normalize_filename(filename) in manifest:
            log.debug("Skipping Notion deletion for proxy file: %s", filename)
            return

        grandparent = parent.parent

        # File deleted from a fund folder
        if grandparent.parent == self.watch_folder:
            fund_name = _resolve_fund_name(parent.name)
            existing_fund = _query_database_by_title(
                self.fund_db_id, fund_name, FUND_TITLE_PROP
            )
            if existing_fund:
                log.info(
                    "File deleted from fund '%s': %s",
                    fund_name, filename,
                )
                threading.Thread(
                    target=_remove_file_from_page,
                    args=(existing_fund["id"], filename),
                    daemon=True,
                ).start()
            return

        # File deleted from a firm folder
        if parent.parent == self.watch_folder:
            firm_name = parent.name
            existing_firm = _query_database_by_title(
                self.firm_db_id, firm_name, FIRM_TITLE_PROP
            )
            if existing_firm:
                log.info(
                    "File deleted from firm '%s': %s",
                    firm_name, filename,
                )
                threading.Thread(
                    target=_remove_file_from_firm_property,
                    args=(existing_firm["id"], filename),
                    daemon=True,
                ).start()

    def on_moved(self, event):
        """Handle file or folder rename/move — update Notion accordingly."""
        old_path = Path(event.src_path)
        new_path = Path(event.dest_path)

        if event.is_directory:
            self._handle_folder_rename(old_path, new_path)
        else:
            self._handle_file_rename(old_path, new_path)

    def _handle_folder_rename(self, old_path: Path, new_path: Path):
        """Handle a folder being renamed."""
        parent = old_path.parent

        # Firm folder renamed (direct child of watch folder)
        if parent == self.watch_folder:
            old_name = old_path.name
            new_name = new_path.name
            existing_firm = _query_database_by_title(
                self.firm_db_id, old_name, FIRM_TITLE_PROP
            )
            if existing_firm:
                log.info("Firm folder renamed: '%s' -> '%s'", old_name, new_name)
                threading.Thread(
                    target=_rename_page_title,
                    args=(existing_firm["id"], new_name, FIRM_TITLE_PROP),
                    daemon=True,
                ).start()
            return

        # Fund folder renamed (child of a firm folder)
        if parent.parent == self.watch_folder:
            old_parsed = parse_fund_folder_name(old_path.name)
            new_parsed = parse_fund_folder_name(new_path.name)

            # Determine old fund name to look up in Notion
            old_fund_name = old_parsed[0] if old_parsed else old_path.name

            # Determine new fund name and identifier
            if new_parsed:
                new_fund_name, new_identifier = new_parsed
            else:
                # No identifier in new name — use full folder name, clear identifier
                new_fund_name = new_path.name
                new_identifier = ""

            existing_fund = _query_database_by_title(
                self.fund_db_id, old_fund_name, FUND_TITLE_PROP
            )
            if existing_fund:
                log.info(
                    "Fund folder renamed: '%s' -> '%s'",
                    old_path.name, new_path.name,
                )

                def _rename_fund(page_id, name, identifier):
                    _rename_page_title(page_id, name, FUND_TITLE_PROP)
                    _update_page_properties(page_id, {
                        "Identifier": {
                            "rich_text": [
                                {"type": "text", "text": {"content": identifier}}
                            ] if identifier else []
                        },
                    })

                threading.Thread(
                    target=_rename_fund,
                    args=(existing_fund["id"], new_fund_name, new_identifier),
                    daemon=True,
                ).start()

    def _handle_file_rename(self, old_path: Path, new_path: Path):
        """Handle a file being renamed — delete old from Notion, upload new."""
        old_parent = old_path.parent
        new_parent = new_path.parent

        # File renamed within a fund folder
        if (old_parent == new_parent
                and old_parent.parent.parent == self.watch_folder):
            fund_name = _resolve_fund_name(old_parent.name)
            existing_fund = _query_database_by_title(
                self.fund_db_id, fund_name, FUND_TITLE_PROP
            )
            if existing_fund:
                    log.info(
                        "File renamed in fund '%s': '%s' -> '%s'",
                        fund_name, old_path.name, new_path.name,
                    )

                    def _rename_fund_file(page_id, old_name, new_file):
                        _remove_file_from_page(page_id, old_name)
                        section_callouts = _find_section_callout_ids(page_id)
                        if section_callouts:
                            _upload_files_to_sections(
                                page_id, [new_file], section_callouts
                            )
                        else:
                            _upload_and_attach_files(page_id, [new_file])

                    threading.Thread(
                        target=_rename_fund_file,
                        args=(existing_fund["id"], old_path.name, new_path),
                        daemon=True,
                    ).start()
            return

        # File renamed within a firm folder
        if (old_parent == new_parent
                and old_parent.parent == self.watch_folder):
            firm_name = old_parent.name
            existing_firm = _query_database_by_title(
                self.firm_db_id, firm_name, FIRM_TITLE_PROP
            )
            if existing_firm:
                log.info(
                    "File renamed in firm '%s': '%s' -> '%s'",
                    firm_name, old_path.name, new_path.name,
                )

                def _rename_firm_file(page_id, old_name, new_file):
                    _remove_file_from_firm_property(page_id, old_name)
                    _upload_firm_files_to_property(page_id, [new_file])

                threading.Thread(
                    target=_rename_firm_file,
                    args=(existing_firm["id"], old_path.name, new_path),
                    daemon=True,
                ).start()


# =========================
# FILE DOWNLOAD (Notion → Local)
# =========================

# Poll intervals (seconds)
POLL_INTERVAL_FAST = 30      # For newly created pages
POLL_INTERVAL_SLOW = 30     # For routine modification checks
FAST_WINDOW_SECONDS = 600    # Pages created within this window get fast polling


def _sanitize_for_pdf(text: str) -> str:
    """Sanitize text for PDF rendering with Helvetica (latin-1 compatible).

    Replaces common Unicode characters with ASCII equivalents and strips
    characters outside the font's supported range.
    """
    # Common substitutions
    replacements = {
        "\u2022": "-",   # bullet •
        "\u2013": "-",   # en dash –
        "\u2014": "--",  # em dash —
        "\u2018": "'",   # left single quote '
        "\u2019": "'",   # right single quote '
        "\u201c": '"',   # left double quote "
        "\u201d": '"',   # right double quote "
        "\u2026": "...", # ellipsis …
        "\u00a0": " ",   # non-breaking space
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    # Strip any remaining non-latin-1 characters (above U+00FF)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _setup_pdf() -> "FPDF":
    """Create an FPDF instance with a Unicode-capable font if available."""
    try:
        from fpdf import FPDF
    except ImportError:
        raise ImportError(
            "fpdf2 is required for PDF export. Install it with: poetry add fpdf2"
        )

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Try to use Arial TTF for better Unicode support
    if os.name == "nt":
        fonts_dir = Path(os.environ.get("WINDIR", r"C:\Windows")) / "Fonts"
    else:
        fonts_dir = Path("/usr/share/fonts/truetype/msttcorefonts")
    arial = fonts_dir / "arial.ttf"
    arial_bold = fonts_dir / "arialbd.ttf"
    arial_italic = fonts_dir / "ariali.ttf"
    arial_bi = fonts_dir / "arialbi.ttf"

    if arial.exists():
        try:
            pdf.add_font("Arial", "", str(arial))
            if arial_bold.exists():
                pdf.add_font("Arial", "B", str(arial_bold))
            if arial_italic.exists():
                pdf.add_font("Arial", "I", str(arial_italic))
            if arial_bi.exists():
                pdf.add_font("Arial", "BI", str(arial_bi))
            pdf._font_family = "Arial"
            log.debug("Using Arial TTF for PDF rendering")
            return pdf
        except Exception:
            log.debug("Failed to load Arial TTF, falling back to Helvetica")

    return pdf


def _pdf_font(pdf) -> str:
    """Return the font family name to use for this PDF instance."""
    # Check if Arial TTF was loaded
    if "arial" in pdf.fonts:
        return "Arial"
    return "Helvetica"


def _pdf_write(pdf, width, height, text: str):
    """Write text to PDF, sanitizing if using a non-Unicode font."""
    font_family = _pdf_font(pdf)
    if font_family == "Helvetica":
        text = _sanitize_for_pdf(text)
    pdf.multi_cell(width, height, text)


def _export_subpage_as_pdf(page_id: str, title: str, dest: Path):
    """
    Export a Notion sub-page as a PDF file.

    Reads all block content from the page and renders it directly to PDF.
    """
    pdf = _setup_pdf()
    font = _pdf_font(pdf)
    pdf.add_page()

    # Title
    pdf.set_font(font, "B", 16)
    _pdf_write(pdf, 0, 10, title)
    pdf.ln(4)

    _render_blocks_to_pdf(pdf, page_id)

    dest.parent.mkdir(parents=True, exist_ok=True)
    # Suppress verbose font subsetting logs from fontTools during PDF output
    fonttools_logger = logging.getLogger("fontTools")
    prev_level = fonttools_logger.level
    fonttools_logger.setLevel(logging.WARNING)
    try:
        pdf.output(str(dest))
    finally:
        fonttools_logger.setLevel(prev_level)
    log.info("Exported sub-page '%s' as PDF -> %s", title, dest.name)


def _render_blocks_to_pdf(pdf, block_id: str, indent: int = 0):
    """Render Notion blocks to a FPDF document."""
    font = _pdf_font(pdf)
    start_cursor = None
    numbered_idx = 0

    while True:
        params = {"page_size": 100}
        if start_cursor:
            params["start_cursor"] = start_cursor
        data = _notion_request(
            "get", f"/blocks/{block_id}/children", params=params
        )
        for block in data.get("results", []):
            btype = block.get("type", "")
            block_data = block.get(btype, {})
            rich_text = block_data.get("rich_text", [])
            text = "".join(t.get("plain_text", "") for t in rich_text)

            left_margin = 10 + indent * 8

            if btype == "heading_1":
                pdf.ln(4)
                pdf.set_font(font, "B", 14)
                pdf.set_x(left_margin)
                _pdf_write(pdf, 0, 7, text)
                pdf.ln(2)
                numbered_idx = 0
            elif btype == "heading_2":
                pdf.ln(3)
                pdf.set_font(font, "B", 12)
                pdf.set_x(left_margin)
                _pdf_write(pdf, 0, 6, text)
                pdf.ln(1)
                numbered_idx = 0
            elif btype == "heading_3":
                pdf.ln(2)
                pdf.set_font(font, "BI", 11)
                pdf.set_x(left_margin)
                _pdf_write(pdf, 0, 6, text)
                numbered_idx = 0
            elif btype in ("paragraph", "quote"):
                pdf.set_font(font, "", 10)
                pdf.set_x(left_margin)
                if text:
                    _pdf_write(pdf, 0, 5, text)
                else:
                    pdf.ln(3)
                numbered_idx = 0
            elif btype == "bulleted_list_item":
                pdf.set_font(font, "", 10)
                pdf.set_x(left_margin + 4)
                _pdf_write(pdf, 0, 5, f"-  {text}")
                numbered_idx = 0
            elif btype == "numbered_list_item":
                numbered_idx += 1
                pdf.set_font(font, "", 10)
                pdf.set_x(left_margin + 4)
                _pdf_write(pdf, 0, 5, f"{numbered_idx}.  {text}")
            elif btype == "to_do":
                checked = block_data.get("checked", False)
                mark = "[x]" if checked else "[ ]"
                pdf.set_font(font, "", 10)
                pdf.set_x(left_margin + 4)
                _pdf_write(pdf, 0, 5, f"{mark}  {text}")
                numbered_idx = 0
            elif btype == "callout":
                pdf.set_font(font, "I", 10)
                pdf.set_x(left_margin + 4)
                if text:
                    _pdf_write(pdf, 0, 5, f"| {text}")
                numbered_idx = 0
            elif btype == "divider":
                y = pdf.get_y()
                pdf.line(left_margin, y, 200, y)
                pdf.ln(3)
                numbered_idx = 0
            elif btype == "table":
                pdf.set_font(font, "", 9)
                table_data = _notion_request(
                    "get", f"/blocks/{block['id']}/children",
                    params={"page_size": 100},
                )
                for row in table_data.get("results", []):
                    cells = row.get("table_row", {}).get("cells", [])
                    cell_texts = [
                        "".join(t.get("plain_text", "") for t in cell)
                        for cell in cells
                    ]
                    pdf.set_x(left_margin)
                    _pdf_write(pdf, 0, 5, " | ".join(cell_texts))
                pdf.ln(2)
                numbered_idx = 0
            else:
                # Unknown block type with text
                if text:
                    pdf.set_font(font, "", 10)
                    pdf.set_x(left_margin)
                    _pdf_write(pdf, 0, 5, text)
                numbered_idx = 0

            # Recurse into children (except tables, handled above)
            if block.get("has_children") and btype not in ("table",):
                _render_blocks_to_pdf(pdf, block["id"], indent + 1)

        if not data.get("has_more"):
            break
        start_cursor = data.get("next_cursor")


def _collect_file_urls_from_block(block_id: str, recurse_into: set[str] | None = None) -> list[dict]:
    """
    Collect downloadable file URLs and sub-page references from a block's children.

    Args:
        block_id: Parent block (page or callout) to scan
        recurse_into: Block types to recurse into (e.g. {"callout"})

    Returns:
        List of dicts, each either:
          - {"name": filename, "url": download_url}              (file)
          - {"name": "Title.pdf", "page_id": id, "title": title} (sub-page)
    """
    if recurse_into is None:
        recurse_into = {"callout"}

    file_block_types = {"file", "pdf", "image", "audio", "video"}
    files = []
    start_cursor = None

    while True:
        params = {"page_size": 100}
        if start_cursor:
            params["start_cursor"] = start_cursor
        data = _notion_request(
            "get", f"/blocks/{block_id}/children", params=params
        )
        for block in data.get("results", []):
            btype = block.get("type", "")

            # Sub-pages → export as PDF
            if btype == "child_page":
                title = block.get("child_page", {}).get("title", "")
                if title:
                    files.append({
                        "name": f"{title}.pdf",
                        "page_id": block["id"],
                        "title": title,
                    })
                continue

            # Recurse into callouts (Data Packs sections)
            if btype in recurse_into and block.get("has_children"):
                files.extend(
                    _collect_file_urls_from_block(block["id"], recurse_into)
                )
                continue

            if btype not in file_block_types:
                continue

            block_data = block.get(btype, {})

            # Notion file blocks have an inner type: "file" (hosted)
            # or "file_upload" (user-uploaded). Extract URL from either.
            inner_type = block_data.get("type", "")
            if inner_type == "file":
                url = block_data.get("file", {}).get("url")
            elif inner_type == "file_upload":
                url = block_data.get("file_upload", {}).get("url")
            else:
                # Fallback: try both
                url = (block_data.get("file", {}).get("url")
                       or block_data.get("file_upload", {}).get("url"))
            if not url:
                continue

            name = block_data.get("name")
            if not name:
                name = _extract_filename_from_url(url)
            if not name:
                continue

            files.append({"name": name, "url": url})

        if not data.get("has_more"):
            break
        start_cursor = data.get("next_cursor")

    return files


def _download_file(url: str, dest: Path):
    """Download a file from a URL to a local path."""
    resp = requests.get(url, stream=True, timeout=120)
    resp.raise_for_status()
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "wb") as f:
        for chunk in resp.iter_content(chunk_size=8192):
            f.write(chunk)
    log.info("Downloaded '%s'", dest.name)


def _get_meeting_notes_items(page_id: str) -> list[dict]:
    """
    Fetch pages linked via the 'Meeting Notes' relation property on a fund page.

    Returns a list of dicts: {"name": "Title.pdf", "page_id": id, "title": title}
    """
    items = []
    try:
        page_data = _notion_request("get", f"/pages/{page_id}")
    except Exception as e:
        log.error("Failed to fetch page %s for Meeting Notes: %s", page_id, e)
        return items

    relations = (
        page_data.get("properties", {})
        .get("Meeting Notes", {})
        .get("relation", [])
    )
    for rel in relations:
        try:
            meeting_page = _notion_request("get", f"/pages/{rel['id']}")
        except Exception as e:
            log.error("Failed to fetch meeting note page %s: %s", rel["id"], e)
            continue

        # Extract title from the meeting notes page (try common title property names)
        props = meeting_page.get("properties", {})
        title = ""
        for prop_name, prop_val in props.items():
            if prop_val.get("type") == "title":
                title_parts = prop_val.get("title", [])
                title = "".join(t.get("plain_text", "") for t in title_parts)
                break

        if title:
            items.append({
                "name": f"{title}.pdf",
                "page_id": rel["id"],
                "title": title,
            })
        else:
            log.warning("Meeting note page %s has no title, skipping", rel["id"])

    return items


def _sync_files_from_notion_page(page_id: str, local_folder: Path):
    """
    Download files and export sub-pages from a Notion fund page to the local folder.

    Maintains a proxy manifest to track Notion-origin files:
      - Files uploaded directly to Notion (not from the folder)
      - Meeting note PDFs exported from relation properties
      - Nested page PDFs exported from child_page blocks

    Origin rules:
      - Notion-origin: file was first seen on Notion and downloaded by the poller.
        Tracked in the manifest. Deleted locally when removed from Notion.
      - Folder-origin: file existed locally before the poller downloaded it (i.e.
        it was uploaded to Notion from the folder). NOT tracked in the manifest.
        Never auto-deleted locally, even if removed from Notion.
    """
    if not local_folder.exists():
        log.warning("Local folder does not exist, skipping download: %s", local_folder)
        return

    # Collect remote items: file blocks, child pages, and Meeting Notes relations
    remote_items = _collect_file_urls_from_block(page_id)
    meeting_items = _get_meeting_notes_items(page_id)
    remote_items.extend(meeting_items)

    # Build a lookup of ALL remote items by normalized name
    remote_names: dict[str, dict] = {}
    for item in remote_items:
        norm = _normalize_filename(item["name"])
        if "page_id" in item:
            remote_names[norm] = {
                "page_id": item["page_id"],
                "title": item["title"],
                "filename": item["name"],
            }
        else:
            remote_names[norm] = {
                "filename": item["name"],
            }

    # Load existing manifest and reconcile
    manifest = _load_proxy_manifest(local_folder)

    # --- Delete stale proxies (in manifest but no longer on Notion) ---
    stale_keys = set(manifest.keys()) - set(remote_names.keys())
    for norm_name in stale_keys:
        entry = manifest[norm_name]
        local_file = local_folder / entry["filename"]
        if local_file.exists():
            # Guard the path so watchdog on_deleted doesn't propagate to Notion
            _guard_path(local_file)
            local_file.unlink()
            log.info(
                "Deleted stale proxy '%s' (removed from Notion)",
                entry["filename"],
            )
        del manifest[norm_name]

    # --- Download new items (only those not already local) ---
    # Files that already exist locally are folder-origin and are NOT added
    # to the manifest, so they will never be auto-deleted.
    existing_local = {
        _normalize_filename(f.name)
        for f in local_folder.iterdir()
        if f.is_file() and f.name != PROXY_MANIFEST_NAME
    }

    for item in remote_items:
        norm = _normalize_filename(item["name"])
        if norm in existing_local:
            continue

        dest = local_folder / item["name"]

        # Guard the path before writing so the watchdog skips it
        _guard_path(dest)

        if "page_id" in item:
            # Sub-page or meeting note → export as PDF
            try:
                _export_subpage_as_pdf(item["page_id"], item["title"], dest)
                manifest[norm] = {
                    "page_id": item["page_id"],
                    "title": item["title"],
                    "filename": item["name"],
                }
            except Exception as e:
                log.error("Failed to export sub-page '%s': %s", item["title"], e)
        else:
            # Regular file uploaded directly to Notion → download and track
            try:
                _download_file(item["url"], dest)
                manifest[norm] = {
                    "filename": item["name"],
                }
            except Exception as e:
                log.error("Failed to download '%s': %s", item["name"], e)

    # Update manifest entries with current remote state
    # (ensures any page_id changes or title renames are captured)
    for norm, info in remote_names.items():
        if norm in manifest:
            manifest[norm] = info

    _save_proxy_manifest(local_folder, manifest)


def _get_fund_page_info(page: dict) -> tuple[str, str, str]:
    """
    Extract fund name, identifier, and firm name from a fund page dict.

    Returns:
        (fund_name, identifier, firm_page_id)
    """
    props = page.get("properties", {})

    # Fund name
    title_parts = props.get(FUND_TITLE_PROP, {}).get("title", [])
    fund_name = "".join(t.get("plain_text", "") for t in title_parts)

    # Identifier
    id_parts = props.get("Identifier", {}).get("rich_text", [])
    identifier = "".join(t.get("plain_text", "") for t in id_parts)

    # AM Firm relation
    relation = props.get("AM Firm", {}).get("relation", [])
    firm_page_id = relation[0]["id"] if relation else ""

    return fund_name, identifier, firm_page_id


def _resolve_local_fund_folder(
    watch_folder: Path, firm_page_id: str, firm_db_id: str,
    fund_name: str,
) -> Path | None:
    """
    Find the local folder path for a fund page.

    Only returns a path if a matching folder already exists on disk.
    Returns None if no corresponding local folder is found (no download
    should happen for fund pages without a local folder).
    """
    # Get firm name from Notion
    if not firm_page_id:
        return None
    try:
        firm_data = _notion_request("get", f"/pages/{firm_page_id}")
    except Exception:
        return None

    firm_props = firm_data.get("properties", {})
    firm_title_parts = firm_props.get(FIRM_TITLE_PROP, {}).get("title", [])
    firm_name = "".join(t.get("plain_text", "") for t in firm_title_parts)
    if not firm_name:
        return None

    firm_folder = watch_folder / firm_name
    if not firm_folder.exists():
        return None

    # Try to find existing fund folder (with or without identifier)
    for sub in firm_folder.iterdir():
        if not sub.is_dir():
            continue
        parsed = parse_fund_folder_name(sub.name)
        if parsed and parsed[0] == fund_name:
            return sub
        if sub.name == fund_name:
            return sub

    # No matching folder found — do not create one
    return None


# =========================
# NOTION DATABASE POLLER
# =========================

class NotionPoller:
    """
    Polls fund pages that have local folders and downloads new files.

    Instead of relying on last_edited_time (which doesn't update when
    child blocks like callout contents change), this poller directly
    compares the set of remote file names against local files.

    Uses two polling speeds:
      - Fast (30s) for pages created within the last 10 minutes
      - Slow (5min) for routine checks on all other pages
    """

    def __init__(
        self,
        watch_folder: Path,
        firm_db_id: str,
        fund_db_id: str,
    ):
        self.watch_folder = watch_folder
        self.firm_db_id = firm_db_id
        self.fund_db_id = fund_db_id
        # page_id -> creation time (ISO string) for fast-poll window
        self._creation_times: dict[str, str] = {}
        # Resolved mappings: page_id -> local_folder (cached, only for pages with folders)
        self._page_folders: dict[str, Path] = {}
        self._stop_event = threading.Event()

    def _query_all_fund_pages(self) -> list[dict]:
        """Query all pages in the fund database."""
        pages = []
        start_cursor = None
        while True:
            body: dict = {"page_size": 100}
            if start_cursor:
                body["start_cursor"] = start_cursor
            data = _notion_request(
                "post", f"/data_sources/{self.fund_db_id}/query", json=body
            )
            pages.extend(data.get("results", []))
            if not data.get("has_more"):
                break
            start_cursor = data.get("next_cursor")
        return pages

    def _is_recently_created(self, created_time: str) -> bool:
        """Check if a page was created within the fast-poll window."""
        from datetime import datetime, timezone
        try:
            created = datetime.fromisoformat(created_time.replace("Z", "+00:00"))
            now = datetime.now(timezone.utc)
            return (now - created).total_seconds() < FAST_WINDOW_SECONDS
        except Exception:
            return False

    def _resolve_pages_with_folders(self):
        """
        Build/refresh the mapping from fund page IDs to local folders.

        Only pages that have a corresponding local folder are tracked.
        """
        try:
            pages = self._query_all_fund_pages()
        except Exception as e:
            log.error("Failed to query fund pages: %s", e)
            return

        self._page_folders.clear()
        for page in pages:
            page_id = page["id"]
            created_time = page.get("created_time", "")
            if page_id not in self._creation_times:
                self._creation_times[page_id] = created_time

            fund_name, _, firm_page_id = _get_fund_page_info(page)
            if not fund_name:
                continue

            local_folder = _resolve_local_fund_folder(
                self.watch_folder, firm_page_id, self.firm_db_id,
                fund_name,
            )
            if local_folder and local_folder.exists():
                self._page_folders[page_id] = local_folder

            # Small delay between pages to avoid API call bursts
            time.sleep(0.3)

        log.info(
            "Poller: tracking %d fund page(s) with local folders",
            len(self._page_folders),
        )

    def _poll_once(self):
        """
        Run one poll cycle: for each tracked page, compare remote files
        against local files and download any missing ones.
        """
        for page_id, local_folder in self._page_folders.items():
            if self._stop_event.is_set():
                break
            if not local_folder.exists():
                continue
            try:
                _sync_files_from_notion_page(page_id, local_folder)
            except Exception as e:
                log.error(
                    "Error syncing page %s to %s: %s",
                    page_id, local_folder, e,
                )
            # Pace API calls between pages
            time.sleep(0.5)

    def _get_sleep_interval(self) -> int:
        """
        Return the appropriate poll interval.

        Uses fast interval if any tracked page was recently created.
        """
        for created_time in self._creation_times.values():
            if self._is_recently_created(created_time):
                return POLL_INTERVAL_FAST
        return POLL_INTERVAL_SLOW

    def run(self):
        """Run the poller loop (blocking). Call stop() from another thread."""
        log.info(
            "Notion poller started (fast=%ds, slow=%ds)",
            POLL_INTERVAL_FAST, POLL_INTERVAL_SLOW,
        )

        # Build initial page-to-folder mapping and poll immediately
        self._resolve_pages_with_folders()
        self._poll_once()

        while not self._stop_event.is_set():
            interval = self._get_sleep_interval()
            if self._stop_event.wait(timeout=interval):
                break
            # Periodically refresh the folder mapping (picks up new local folders)
            self._resolve_pages_with_folders()
            self._poll_once()

        log.info("Notion poller stopped.")

    def stop(self):
        """Signal the poller to stop."""
        self._stop_event.set()


# =========================
# ENTRY POINTS
# =========================

def initial_scan(watch_folder: Path, firm_db_id: str, fund_db_id: str):
    """Scan existing folders and sync any that aren't yet in Notion."""
    if not watch_folder.exists():
        log.warning("Watch folder does not exist: %s", watch_folder)
        return

    for firm_folder in watch_folder.iterdir():
        if firm_folder.is_dir():
            sync_firm(firm_folder, firm_db_id, fund_db_id)


def watch_folder(folder_path: Path | str | None = None):
    """
    Start monitoring a folder for new firm/fund directories.

    Args:
        folder_path: Path to monitor. Defaults to DEFAULT_WATCH_FOLDER.
    """
    watch_path = Path(folder_path) if folder_path else DEFAULT_WATCH_FOLDER
    log.info("Watch folder: %s", watch_path)

    if not watch_path.exists():
        watch_path.mkdir(parents=True, exist_ok=True)
        log.info("Created watch folder: %s", watch_path)

    # Auto-discover databases
    log.info("Discovering Notion databases...")
    firm_db_id, fund_db_id = discover_databases()

    # Initial scan of existing folders
    log.info("Running initial scan...")
    initial_scan(watch_path, firm_db_id, fund_db_id)

    # Set up watchdog (local → Notion)
    handler = NotionFolderHandler(watch_path, firm_db_id, fund_db_id)
    observer = Observer()
    observer.schedule(handler, str(watch_path), recursive=True)
    observer.start()

    # Set up Notion poller (Notion → local)
    poller = NotionPoller(watch_path, firm_db_id, fund_db_id)
    poller_thread = threading.Thread(target=poller.run, daemon=True)
    poller_thread.start()

    log.info("Watching for changes... (Ctrl+C to stop)")

    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        log.info("Stopping watcher...")
        poller.stop()
        observer.stop()
    observer.join()
    log.info("Watcher stopped.")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Sync local firm/fund folders to Notion databases."
    )
    parser.add_argument(
        "--folder",
        type=str,
        default=None,
        help="Path to the folder to monitor (default: built-in path)",
    )
    args = parser.parse_args()

    watch_folder(args.folder)
